FROM node:12-alpine AS builder

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
#COPY templates ./templates/
#COPY views ./views/


# Install app dependencies
RUN npm install


COPY . .

RUN npm run build

FROM node:12-alpine

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/templates ./templates
COPY --from=builder /app/views ./views
COPY --from=builder /app/public ./public


EXPOSE 3000
CMD [ "npm", "run", "start:prod" ]